services:
  github-runner:
    build: .
    container_name: github-runner
    restart: unless-stopped
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - RUNNER_NAME=homelab-runner
      - RUNNER_LABELS=self-hosted,linux,x64,homelab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-data:/actions-runner/_work
    network_mode: host

volumes:
  runner-data: